force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This custom object will be utilized in the JobQuest app to track job applications for the user seeking a job.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is for listing the status of the job application.</description>
    <inlineHelpText>Please select one status for the job application.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public with sharing class JobApplicationTriggerHandler extends TriggerHandler {
    private List<Job_Application__c>newJobList;
    private Map<Id, Job_Application__c>newJobMap;
    private List<Job_Application__c>oldJobList;
    private Map<Id, Job_Application__c>oldJobMap;

    public JobApplicationTriggerHandler() {
        this.newJobList = (List<Job_Application__c>)Trigger.new;
        this.newJobMap = (Map<Id, Job_Application__c>)Trigger.newMap;
        this.oldJobList = (List<Job_Application__c>)Trigger.old;
        this.oldJobMap = (Map<Id, Job_Application__c>)Trigger.oldMap;

    }
    public override void beforeInsert() {

    }
        

    public override void beforeUpdate() {

    }

    public override void beforeDelete () {

    }

    public override void afterInsert () {
        List<Task> tasksToInsert = new List<Task>();
        Task newTask = new Task();
        
        for (Job_Application__c job : this.newJobMap.values()) {
            job = newJobMap.get(job.Id);
            switch on job.Status__c {
            when 'Saved' {
                newTask.Subject = 'Alignment with Interest and Values';
                newTask.WhatId = job.Id;
                newTask.ActivityDate = Date.Today().addDays(2);
                newTask.Priority = 'High';
                newTask.OwnerId = job.OwnerId;
                newTask.Status = 'Not Started';
                tasksToInsert.add(newTask);
            }
            //when 'Status2' {
                //newTask.Subject = 'Task for Status2';
                
            }
            //when ''
            //when else {
              //  newTask.Subject = 'Default Task';
                
        }
        insert tasksToInsert;

    }
        


   

    public override void afterUpdate() {


    } 

    public override void afterDelete () {

    }

    public override void afterUndelete () {


    }




}