force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This custom object will be utilized in the JobQuest app to track job applications for the user seeking a job.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>Follow-up date: A date field to specify when to follow up on the application.</description>
    <inlineHelpText>When should you follow up on this application?</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This is a text field for the job position or title to which the user is applying.</description>
    <inlineHelpText>Please record the job position or title here.</inlineHelpText>
    <label>Job Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Notes: A text field that can hold a lot of information.</description>
    <inlineHelpText>Please record additional information or any observations.</inlineHelpText>
    <label>Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This field is for listing the status of the job application.</description>
    <inlineHelpText>Please select one status for the job application.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleJobApplicationBatch_Test.cls
@isTest
private class ScheduleJobApplicationBatch_Test {

    private static List<Job_Application__c> createTestApplications(Integer count) {
        List<Job_Application__c> applications = new List<Job_Application__c>();
        
        for (Integer i = 0; i < count; i++) {
            applications.add(new Job_Application__c(
                Status__c = (i < 5) ? 'Applied' : 'Accepted', 
                Follow_up_Date__c = Date.today().addDays(-35), 
                Notes__c = 'Test note ' + i,
                Job_Title__c = 'Test SF Dev job ' + i
            ));
        }
        insert applications;
        return applications; // Return the created applications
    }

    @isTest static void ScheduleJobApplicationBatchTest() {
        createTestApplications(10);

        Test.startTest();
        String cron = '0 0 1,15 * * ?';  // This runs at midnight on the 1st and 15th of every month
        String jobName = 'TestScheduledJob';
        ScheduleJobApplicationBatch job = new ScheduleJobApplicationBatch();
        System.schedule(jobName, cron, job);
        Test.stopTest();

        CronTrigger[] scheduledJobs = [SELECT Id, CronExpression, State FROM CronTrigger WHERE CronExpression = :cron];
        System.assertEquals(1, scheduledJobs.size(), 'Expected one scheduled job with the given cron expression.');
        System.assertEquals('WAITING', scheduledJobs[0].State, 'Expected the job to be in WAITING state.');
    }
}