force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This custom object will be utilized in the JobQuest app to track job applications for the user seeking a job.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <description>Description: A long text area to hold detailed information about the job, such as responsibilities, qualifications, benefits, etc.</description>
    <inlineHelpText>This field is for the detailed job description.</inlineHelpText>
    <label>Job Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This is a text field for the job position or title to which the user is applying.</description>
    <inlineHelpText>Please record the job position or title here.</inlineHelpText>
    <label>Job Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location: A text field to indicate the job location or if it&apos;s remote.</description>
    <inlineHelpText>Please indicate job location or if job is remote.</inlineHelpText>
    <label>Location</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JoobleBringMeJobsTest.cls
@isTest
private class JoobleBringMeJobsTest {
    
    // Implement mock callout class
    private class MockJoobleResponse implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);//testing for best scenerio will also need to test for when it doesn't work 
           
            res.setBody('{"totalCount":1,"jobs":[{"title":"Salesforce Developer","location":"Remote","snippet":"Job description...","salary":"1000","link":"https://joblink.com","company":"TechCorp","id":"1234","updated":"2023-10-21T10:10:10Z"}]}');
            return res;
        }
    }
    
    @isTest static void testBringMeJobs() {
        Test.setMock(HttpCalloutMock.class, new MockJoobleResponse());
        
        Test.startTest();
        JoobleBringMeJobs.fetchJobs(); 
        Test.stopTest();
        
        List<Job_Application__c> insertedJobs = [SELECT Job_Title__c, Location__c, Job_Description__c FROM Job_Application__c];
        Assert.areEqual(1, insertedJobs.size(), 'Expected 1 job listing to be inserted.');
        Assert.areEqual('Salesforce Developer', insertedJobs[0].Job_Title__c);
        Assert.areEqual('Remote', insertedJobs[0].Location__c);
        Assert.areEqual('Job description...', insertedJobs[0].Job_Description__c);
    }
}