force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>This custom object will be utilized in the JobQuest app to track job applications for the user seeking a job.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A text or lookup field to store the name of the company or nonprofit where the job application is being sent.</description>
    <inlineHelpText>To which company or organization will this application be sent?</inlineHelpText>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <description>This is a text field for the name of the employer</description>
    <label>Employer</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>Follow-up date: A date field to specify when to follow up on the application.</description>
    <inlineHelpText>When should you follow up on this application?</inlineHelpText>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>This is a text field for the job position or title to which the user is applying.</description>
    <inlineHelpText>Please record the job position or title here.</inlineHelpText>
    <label>Job Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Listing_Pay__c.field-meta.xml
<CustomField>
    <fullName>Listing_Pay__c</fullName>
    <description>string(text) salary directly from job listing, not yet standardized</description>
    <label>Listing Pay</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Salary: A numerical field to capture the expected salary for the job position.  No decimal places.</description>
    <inlineHelpText>Please record the expected salary.  If a range is given pick within the range.  If no salary information is given, record the typical salary for the job position in the given location.</inlineHelpText>
    <label>Salary</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/JobQuestDisplayApex.cls
public with sharing class JobQuestDisplayApex {
    @AuraEnabled(cacheable=true)
    public static List<Job_Application__c> getJobApplications() {
        return [SELECT Job_Title__c, Id, Listing_Pay__c, Salary__c, Employer__c, Company__r.Name, Follow_up_Date__c 
                FROM Job_Application__c];
    }
    @AuraEnabled
    public static void deleteJobApplication(String jobId) {
    delete new Job_Application__c(Id = jobId);
}

}